imgui.ImGuiWindowFlags_NoTitleBar             = 1 << 0   -- Disable title-bar
imgui.ImGuiWindowFlags_NoResize               = 1 << 1   -- Disable user resizing with the lower-right grip
imgui.ImGuiWindowFlags_NoMove                 = 1 << 2   -- Disable user moving the window
imgui.ImGuiWindowFlags_NoScrollbar            = 1 << 3   -- Disable scrollbars (window can still scroll with mouse or programatically)
imgui.ImGuiWindowFlags_NoScrollWithMouse      = 1 << 4   -- Disable user vertically scrolling with mouse wheel
imgui.ImGuiWindowFlags_NoCollapse             = 1 << 5   -- Disable user collapsing window by double-clicking on it
imgui.ImGuiWindowFlags_AlwaysAutoResize       = 1 << 6   -- Resize every window to its content every frame
imgui.ImGuiWindowFlags_ShowBorders            = 1 << 7   -- Show borders around windows and items
imgui.ImGuiWindowFlags_NoSavedSettings        = 1 << 8   -- Never load/save settings in .ini file
imgui.ImGuiWindowFlags_NoInputs               = 1 << 9   -- Disable catching mouse or keyboard inputs
imgui.ImGuiWindowFlags_MenuBar                = 1 << 10  -- Has a menu-bar
imgui.ImGuiWindowFlags_HorizontalScrollbar    = 1 << 11  -- Allow horizontal scrollbar to appear (off by default). You may use SetNextWindowContentSize(ImVec2(width0.0f)); prior to calling Begin() to specify width. Read code in imgui_demo in the "Horizontal Scrolling" section.
imgui.ImGuiWindowFlags_NoFocusOnAppearing     = 1 << 12  -- Disable taking focus when transitioning from hidden to visible state
imgui.ImGuiWindowFlags_NoBringToFrontOnFocus  = 1 << 13  -- Disable bringing window to front when taking focus (e.g. clicking on it or programatically giving it focus)
imgui.ImGuiWindowFlags_AlwaysVerticalScrollbar = 1 << 14  -- Always show vertical scrollbar (even if ContentSize.y < Size.y)
imgui.ImGuiWindowFlags_AlwaysHorizontalScrollbar = 1<< 15  -- Always show horizontal scrollbar (even if ContentSize.x < Size.x)
imgui.ImGuiWindowFlags_AlwaysUseWindowPadding = 1 << 16  -- Ensure child windows without border uses style.WindowPadding (ignored by default for non-bordered child windows because more convenient)